"""create core backend tables

Revision ID: 396445a00e4f
Revises: 
Create Date: 2026-07-15 03:53:46.489120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '396445a00e4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clearance_dependencies',
    sa.Column('clearance_key', sa.Text(), nullable=False),
    sa.Column('depends_on_clearance_key', sa.Text(), nullable=False),
    sa.Column('unlock_on_status', sa.String(), nullable=False),
    sa.Column('residential_only', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("unlock_on_status IN ('approved')", name='ck_clearance_deps_unlock_status'),
    sa.CheckConstraint('clearance_key <> depends_on_clearance_key', name='ck_clearance_deps_not_self'),
    sa.PrimaryKeyConstraint('clearance_key', 'depends_on_clearance_key')
    )
    op.create_index('ix_clearance_deps_key', 'clearance_dependencies', ['clearance_key'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('role_key', sa.String(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('role_scope', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("role_scope IN ('student', 'official', 'admin')", name='ck_roles_scope'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_key'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('role_id', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("account_type IN ('student', 'official', 'admin')", name='ck_users_account_type'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_role_active', 'users', ['role_id', 'is_active'], unique=False)
    op.create_table('officials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('staff_email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('office_phone', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('student_no', sa.String(length=9), nullable=False),
    sa.Column('livingstone_email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('classification', sa.Text(), nullable=True),
    sa.Column('major', sa.Text(), nullable=True),
    sa.Column('residency_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("residency_type IN ('residential', 'commuter')", name='ck_students_residency_type'),
    sa.CheckConstraint("student_no ~ '^100[0-9]{6}$'", name='ck_students_student_no_format'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('livingstone_email'),
    sa.UniqueConstraint('student_no'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_students_user_id', 'students', ['user_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_number', sa.String(length=30), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('term_code', sa.String(length=20), nullable=False),
    sa.Column('academic_year', sa.String(length=9), nullable=False),
    sa.Column('major', sa.Text(), nullable=False),
    sa.Column('classification', sa.Text(), nullable=True),
    sa.Column('housing_required', sa.Boolean(), nullable=False),
    sa.Column('overall_status', sa.String(), nullable=False),
    sa.Column('current_step', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("overall_status IN ('in_progress', 'correction_required', 'rejected', 'in_person_required', 'fully_registered')", name='ck_applications_overall_status'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_number')
    )
    op.create_index('ix_applications_status_step', 'applications', ['overall_status', 'current_step'], unique=False)
    op.create_index('ix_applications_student_submitted', 'applications', ['student_id', 'submitted_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_role_id', sa.SmallInteger(), nullable=True),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('before_state_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('annotation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_actor_time', 'audit_logs', ['actor_user_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_logs_application_time', 'audit_logs', ['application_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('clearances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('clearance_key', sa.Text(), nullable=False),
    sa.Column('clearance_label', sa.Text(), nullable=False),
    sa.Column('office_role_id', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('availability', sa.String(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by_official_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_transition_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("availability IN ('locked', 'ready', 'completed', 'needs_student_action')", name='ck_clearances_availability'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'correction_required', 'rejected', 'in_person_required', 'not_required')", name='ck_clearances_status'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['office_role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_official_id'], ['officials.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'clearance_key', name='uq_clearances_app_key')
    )
    op.create_index('ix_clearances_app_status', 'clearances', ['application_id', 'status'], unique=False)
    op.create_index('ix_clearances_queue', 'clearances', ['office_role_id', 'availability', 'status'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('course_title', sa.Text(), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('credit_hours', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('credit_hours > 0', name='ck_courses_credit_hours_positive'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'course_code', 'section', name='uq_courses_app_code_section')
    )
    op.create_index('ix_courses_application', 'courses', ['application_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('stored_filename', sa.Text(), nullable=False),
    sa.Column('storage_backend', sa.String(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('virus_scan_status', sa.String(), nullable=False),
    sa.Column('review_message', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('supersedes_document_id', sa.UUID(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("status IN ('uploaded', 'approved', 'needs_correction', 'rejected')", name='ck_documents_status'),
    sa.CheckConstraint("storage_backend IN ('local', 's3')", name='ck_documents_storage_backend'),
    sa.CheckConstraint("virus_scan_status IN ('pending', 'clean', 'infected', 'failed')", name='ck_documents_virus_scan_status'),
    sa.CheckConstraint('size_bytes > 0', name='ck_documents_size_positive'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_app_type_status', 'documents', ['application_id', 'document_type', 'status'], unique=False)
    op.create_index('ix_documents_checksum', 'documents', ['checksum_sha256'], unique=False)
    op.create_index('ix_documents_uploader', 'documents', ['uploaded_by_user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=True),
    sa.Column('recipient_role_id', sa.SmallInteger(), nullable=True),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delivery_status', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedupe_key', sa.Text(), nullable=True),
    sa.CheckConstraint("channel IN ('in_app', 'email')", name='ck_notifications_channel'),
    sa.CheckConstraint("delivery_status IN ('pending', 'sent', 'failed', 'read')", name='ck_notifications_delivery_status'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index('ix_notifications_role_unread', 'notifications', ['recipient_role_id', 'is_read', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['recipient_user_id', 'is_read', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index('ix_notifications_role_unread', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_documents_uploader', table_name='documents')
    op.drop_index('ix_documents_checksum', table_name='documents')
    op.drop_index('ix_documents_app_type_status', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_courses_application', table_name='courses')
    op.drop_table('courses')
    op.drop_index('ix_clearances_queue', table_name='clearances')
    op.drop_index('ix_clearances_app_status', table_name='clearances')
    op.drop_table('clearances')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_application_time', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_time', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_applications_student_submitted', table_name='applications')
    op.drop_index('ix_applications_status_step', table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_students_user_id', table_name='students')
    op.drop_table('students')
    op.drop_table('officials')
    op.drop_index('ix_users_role_active', table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index('ix_clearance_deps_key', table_name='clearance_dependencies')
    op.drop_table('clearance_dependencies')
    # ### end Alembic commands ###
